[package]
name = "obfusku-fmt"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Formatter over obfusku-syntax's surface AST. No dependency on obfusku-core, obfusku-typecheck, or obfusku-runtime."
authors.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
obfusku-syntax = { version = "1.0.0", path = "../obfusku-syntax" }
obfusku-diagnostics = { version = "1.0.0", path = "../obfusku-diagnostics" }

[lints]
workspace = true
