[package]
name = "obfusku-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Execution over obfusku-core's Core AST. Deliberately independent of obfusku-syntax and obfusku-typecheck."
authors.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
obfusku-core = { version = "1.0.0", path = "../obfusku-core" }
obfusku-diagnostics = { version = "1.0.0", path = "../obfusku-diagnostics" }

[lints]
workspace = true
